[package]
name = "syn-sem-common"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.67"
description = "Common utilities for syn-sem"
repository = "https://github.com/ecoricemon/syn-sem"

[dependencies]
any-intern = { workspace = true }
fxhash = { workspace = true }
elsa = { workspace = true }
indexmap = { workspace = true }
