[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
syn-sem-common = { path = "crates/syn-sem-common" }
syn-sem-ast = { path = "crates/syn-sem-ast" }
syn-sem-name = { path = "crates/syn-sem-name" }
syn-sem-hir = { path = "crates/syn-sem-hir" }
syn-sem-infer = { path = "crates/syn-sem-infer" }
syn-sem-eval = { path = "crates/syn-sem-eval" }
syn-sem-macros = { path = "crates/syn-sem-macros" }
syn-locator = { git = "https://github.com/ecoricemon/syn-locator.git", rev = "f8f192e9d87fc048f7e81064ff062b288b9cddf2" }
logic-eval = { git = "https://github.com/ecoricemon/logic-eval.git", rev = "b4daaf5617ed86a6722ed4f4e58415e2ad68867d" }
logic-eval-util = { git = "https://github.com/ecoricemon/logic-eval.git", rev = "b4daaf5617ed86a6722ed4f4e58415e2ad68867d" }
any-intern = { git = "https://github.com/ecoricemon/logic-eval.git", rev = "b4daaf5617ed86a6722ed4f4e58415e2ad68867d" }
my-utils = "0.1.1"
syn = "2.0.106"
proc-macro2 = "1.0.91"
quote = "1.0.35"
smallvec = "1.15.1"
parking_lot = "0.10.2"
const_format = "0.2.35"
log = "0.4.28"
hashlink = "0.11.0"
indexmap = "2.11.4"
fxhash = "0.2.1"
once_cell = "1.21.3"
bitflags = "2.11.0"
bumpalo = "3.10.0"
dashmap = "6.1.0"
num-traits = "0.2.19"
elsa = "1.11.2"
