[package]
name = "syn-sem-infer"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.66.1"
description = "Type inference for syn-sem"
repository = "https://github.com/ecoricemon/syn-sem"

[dependencies]
logic-eval = { workspace = true }
syn-sem-common = { workspace = true }
syn-sem-name = { workspace = true }
syn-sem-pr = { workspace = true }

[dev-dependencies]
syn-sem-ast = { workspace = true }
