[package]
name = "syn-sem-infer"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.67"
description = "Type inference for syn-sem"
repository = "https://github.com/ecoricemon/syn-sem"

[dependencies]
logic-eval = { workspace = true }
syn-sem-common = { workspace = true }
syn-sem-macros = { workspace = true }
syn-sem-name = { workspace = true }
syn-sem-hir = { workspace = true }

[dev-dependencies]
criterion = "0.5"
syn-sem-ast = { workspace = true }

[[bench]]
name = "infer"
harness = false
