[package]
name = "syn-sem-forest"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.66.1"
description = "Syntax forest and locator support for syn-sem"
repository = "https://github.com/ecoricemon/syn-sem"

[dependencies]
fxhash = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn-sem-common = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }
syn-locator = { workspace = true, features = ["find"] }
