[package]
name = "syn-sem-ast"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.67"
description = "Syntax for syn-sem"
repository = "https://github.com/ecoricemon/syn-sem"

[dependencies]
syn-sem-common = { workspace = true }
syn-sem-macros = { workspace = true }
any-intern = { workspace = true }
syn-locator = { workspace = true }
bumpalo = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
fxhash = { workspace = true }
num-traits = { workspace = true }
elsa = { workspace = true }
